[package]
name = "flashy-io"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
futures = "0.3.30"
taffy = "0.5.2"
flashy-element = { path = "../element" }
flashy-macros = { path = "../macros" }
uuid = { version = "1.10.0", features = ["v4"] }
derive_more = { version = "1.0.0", features = ["display"] }
