[package]
name = "flashy-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.28.1"
futures = "0.3.30"
taffy = "0.5.2"

[dev-dependencies]
smol = "2.0.1"
