[workspace]
resolver = "2"

members = [
    "packages/element",
    "packages/io",
    "packages/macro",
]

[package]
name = "flashy-examples"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
flashy-io = { path = "packages/io" }
futures = "0.3.30"
smol = "2.0.1"

[[example]]
name = "borders"
path = "examples/borders.rs"
