[package]
name = "iocraft"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.30"
taffy = { version = "0.5.2", default-features = false, features = ["flexbox", "taffy_tree"] }
iocraft-macros = { path = "../iocraft-macros" }
uuid = { version = "1.10.0", features = ["v4"] }
derive_more = { version = "1.0.0", features = ["debug", "display"] }
futures-signals = { version = "0.3.34", default-features = false }
bitflags = "2.6.0"

[dev-dependencies]
indoc = "2"
