[package]
name = "flashy-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
flashy-element = { path = "../element" }
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"

[dev-dependencies]
flashy-io = { path = "../io" }
